### ISSUE TITLE
New links to add

### ISSUE THREAD

**Issue by yorek** [ddneves/awesome-azure-learning#1]
Not 100% sure where the following links should go:

Dedicate Azure SQL and SQL Server workshops
https://microsoft.github.io/sqlworkshops/

Articles on Azure SQL
https://techcommunity.microsoft.com/t5/azure-sql-database/bg-p/Azure-SQL-Database

**Comment by ddneves** [comment]
I will add them into general learning, but I like the point you brought up regarding dedicated pages for products. I will try to build some templating and come back.

**Comment by ddneves** [comment]
added to learning.md
