### ISSUE TITLE
Specific sections for Azure Products?

### ISSUE THREAD

**Issue by yorek** [ddneves/awesome-azure-learning#2]
What about having specific sections for specific Azure Products? For example Azure SQL, Azure Functions etc...

**Comment by ddneves** [comment]
Good point. Will come back to you once templating done.

**Comment by ddneves** [comment]
Hey - I added product reference on the main page and created an initial draft for Azure SQL, Azure Functions and Azure Sentinel in the products folder.

Let me know you feedback via LinkedIn and feel free to add links to that! :-)
